name: circle_flags
description: A collection of round flags
version: 3.0.0
repository: https://github.com/cedvdb/flutter_circle_flags

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  dart_countries: ^3.0.3
  vector_graphics_compiler: ^1.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  assets:
    - assets/optimized/
